service:
  name: wah-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 200
  timeout: 30
  versionFunctions: false
  tags:
    Project: WAH
  tracing:
    apiGateway: true
    lambda: true

functions:
  auctionUpdateLogForRealm:
    tags:
      FunctionName: Wah-auctionUpdateLogForRealm
    handler: src/controllers/auction.getUpdateLogForRealm
    memorySize: 200
    events:
      - http:
          method: get
          path: auction/log/{id}
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  auctionsDownloadAndSave:
    tags:
      FunctionName: Wah-auctionsDownloadAndSave
    handler: src/controllers/auction.auctionsDownloadAndSave
    memorySize: 350
    timeout: 59
  auctionsUpdateStaticS3Data:
    tags:
      FunctionName: Wah-auctions
    handler: src/controllers/auction.updateStaticS3Data
    memorySize: 350
    timeout: 59
  updateAllHouses:
    tags:
      FunctionName: Wah-updateAllHouses
    handler: src/controllers/auction-pooled-connections.updateAll
    memorySize: 256
    timeout: 59

  deactivateInactiveHouses:
    tags:
      FunctionName: Wah-deactivateInactiveHouses
    handler: src/controllers/auction.deactivateInactiveHouses
    memorySize: 200

  updateSpesificHouse:
    tags:
      FunctionName: Wah-updateSpesificHouse
    handler: src/controllers/auction.updateOne
    memorySize: 200
    events:
      - http:
          method: post
          path: auction/update-one
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  deleteOldPriceHistoryForRealmAndSetDailyPrice:
    tags:
      FunctionName: Wah-deleteOldPriceHistoryForRealmAndSetDailyPrice
    handler: src/controllers/auction.deleteOldPriceHistoryForRealmAndSetDailyPrice
    memorySize: 450
    timeout: 60
  updateAllRealmDailyData:
    tags:
      FunctionName: Wah-updateAllRealmDailyData
    handler: src/controllers/auction.updateAllRealmDailyData
    memorySize: 1024
    timeout: 300
  locales:
    tags:
      FunctionName: Wah-locales
    handler: src/controllers/locale.handler
    events:
      - http:
          method: post
          path: locale/add-missing
          cors:
            origin: 'localhost:3000'
  items:
    tags:
      FunctionName: Wah-items
    handler: src/controllers/item.handler
    memorySize: 300
    events:
      - http:
          method: any
          path: item
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'

      - http:
          method: any
          path: item/{id}
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  getPriceHistoryForItem:
    tags:
      FunctionName: Wah-item-history
    handler: src/controllers/item.getPriceHistoryForItem
    memorySize: 256
    events:
      - http:
          method: post
          path: item/history
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  pets:
    tags:
      FunctionName: Wah-pets
    handler: src/controllers/pet.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: pet
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'

      - http:
          method: any
          path: pet/{id}
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  recipes:
    tags:
      FunctionName: Wah-recipes
    handler: src/controllers/recipe.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: recipe
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'

      - http:
          method: any
          path: recipe/{id}
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  zone:
    tags:
      FunctionName: Wah-zone
    handler: src/controllers/zone.getAll
    memorySize: 128
    timeout: 30
    events:
      - http:
          method: post
          path: zone
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  npcGetById:
    tags:
      FunctionName: Wah-npc-by-id
    handler: src/controllers/npc.getById
    memorySize: 128
    events:
      - http:
          method: post
          path: npc/{id}
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  npcGetAll:
    tags:
      FunctionName: Wah-npc-get-all
    handler: src/controllers/npc.getAll
    memorySize: 400
    events:
      - http:
          method: post
          path: npc/all
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  npcGetByIds:
    tags:
      FunctionName: Wah-npc
    handler: src/controllers/npc.addNewNPCsByIds
    memorySize: 256
    timeout: 30
    events:
      - http:
          method: post
          path: npc
          cors:
            origin: 'http://localhost:4200'
  character:
    tags:
      FunctionName: Wah-character
    handler: src/controllers/character.handler
    memorySize: 128
    events:
      - http:
          method: post
          path: character
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  realm:
    tags:
      FunctionName: Wah-realm
    handler: src/controllers/realm.handler
    events:
      - http:
          method: post
          path: realm
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'

  realmAllRegions:
    tags:
      FunctionName: Wah-realmAllRegions
    handler: src/controllers/realm.realmAllRegions
    memorySize: 200
    events:
      - http:
          method: get
          path: realm/all
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  getByRegionAndName:
    tags:
      FunctionName: Wah-getByRegionAndName
    handler: src/controllers/realm.getByRegionAndName
    memorySize: 200
    events:
      - http:
          method: get
          path: realm/{region}/{realm}
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  test:
    tags:
      FunctionName: Wah-test
    handler: src/controllers/test.handler
    memorySize: 512
    events:
      - http:
          method: get
          path: test
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'

  logger:
    tags:
      FunctionName: Wah-logger
    handler: src/controllers/logger.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: logger
  loggerClientEvent:
    tags:
      FunctionName: Wah-loggerClientEvent
    handler: src/controllers/logger.clientEvent
    memorySize: 128
   # TODO: See if this affects costs
   # events:
   #   - http:
   #       method: post
   #       path: logger/client-event
   #       cors:
   #         origin: 'http://localhost:4200,https://wah.jonaskf.net'

  loggerClientDelete:
    tags:
      FunctionName: Wah-loggerClientDelete
    handler: src/controllers/logger.clientDelete
    memorySize: 128
    events:
      - http:
          method: delete
          path: logger/client-event
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  currency:
    tags:
      FunctionName: Wah-currencies
    handler: src/controllers/currency.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: currency
          cors:
            origin: 'http://localhost:4200'
  updateTSMDumpData:
    tags:
      FunctionName: Wah-updateTSMDumpData
    handler: src/controllers/tsm.handler
    memorySize: 256
