service:
  name: wah-api

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 200
  timeout: 30
  versionFunctions: false
  #tags:
    #Project: WAH
  tracing:
    apiGateway: true
    lambda: true

functions:
  auctionUpdateLogForRealm:
    tags:
      Function: Wah-auctionUpdateLogForRealm
    handler: src/controllers/auction.getUpdateLogForRealm
    memorySize: 200
    events:
      - http:
          method: get
          path: auction/log/{id}
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  auctionsDownloadAndSave:
    tags:
      Function: Wah-auctionsDownloadAndSave
    handler: src/controllers/auction.auctionsDownloadAndSave
    memorySize: 350
    timeout: 59
  auctionsUpdateStaticS3Data:
    tags:
      Function: Wah-auctions
    handler: src/controllers/auction.updateStaticS3Data
    memorySize: 350
    timeout: 59
  updateAllHouses:
    tags:
      Function: Wah-updateAllHouses
    handler: src/controllers/auction.updateAll
    memorySize: 256
    timeout: 59

  deactivateInactiveHouses:
    tags:
      Function: Wah-deactivateInactiveHouses
    handler: src/controllers/auction.deactivateInactiveHouses
    memorySize: 200

  updateSpesificHouse:
    tags:
      Function: Wah-updateSpesificHouse
    handler: src/controllers/auction.updateOne
    memorySize: 200
    events:
      - http:
          method: post
          path: auction/update-one
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  deleteOldPriceHistoryForRealmAndSetDailyPrice:
    tags:
      Function: Wah-deleteOldPriceHistoryForRealmAndSetDailyPrice
    handler: src/controllers/auction.deleteOldPriceHistoryForRealmAndSetDailyPrice
    memorySize: 450
    timeout: 120
  updateAllRealmDailyData:
    tags:
      Function: Wah-updateAllRealmDailyData
    handler: src/controllers/auction.updateAllRealmDailyData
    memorySize: 1024
    timeout: 300
  locales:
    tags:
      Function: Wah-locales
    handler: src/controllers/locale.handler
    events:
      - http:
          method: post
          path: locale/add-missing
          cors:
            origin: 'localhost:3000'
  items:
    tags:
      Function: Wah-items
    handler: src/controllers/item.handler
    memorySize: 300
    events:
      - http:
          method: any
          path: item
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'

      - http:
          method: any
          path: item/{id}
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  getPriceHistoryForItem:
    tags:
      Function: Wah-item-history
    handler: src/controllers/item.getPriceHistoryForItem
    memorySize: 256
    events:
      - http:
          method: post
          path: item/history
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  pets:
    tags:
      Function: Wah-pets
    handler: src/controllers/pet.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: pet
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'

      - http:
          method: any
          path: pet/{id}
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  getProfessions:
    tags:
      FunctionName: Wah-getProfessions
    memorySize: 128
    handler: src/profession/controller.getProfessions
    events:
      - http:
          method: post
          path: profession
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  getAllRecipesAfter:
    tags:
      FunctionName: Wah-getAllRecipesAfter
    memorySize: 128
    handler: src/recipe/controller.getAfter
    events:
      - http:
          method: post
          path: recipe
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'

  getRecipeById:
    tags:
      FunctionName: Wah-getRecipeById
    memorySize: 128
    handler: src/recipe/controller.getById
    events:
      - http:
          method: post
          path: recipe/{id}
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'

  zone:
    tags:
      Function: Wah-zone
    handler: src/controllers/zone.getAll
    memorySize: 128
    timeout: 30
    events:
      - http:
          method: post
          path: zone
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  npcGetById:
    tags:
      Function: Wah-npc-by-id
    handler: src/controllers/npc.getById
    memorySize: 128
    events:
      - http:
          method: post
          path: npc/{id}
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  npcGetAll:
    tags:
      Function: Wah-npc-get-all
    handler: src/controllers/npc.getAll
    memorySize: 400
    events:
      - http:
          method: post
          path: npc/all
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  npcGetByIds:
    tags:
      Function: Wah-npc
    handler: src/controllers/npc.addNewNPCsByIds
    memorySize: 256
    timeout: 30
    events:
      - http:
          method: post
          path: npc
          cors:
            origin: 'http://localhost:4200'
  character:
    tags:
      FunctionName: Wah-character
    handler: src/character/controller.getCharacter
    memorySize: 128
    events:
      - http:
          method: post
          path: character
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  realm:
    tags:
      Function: Wah-realm
    handler: src/controllers/realm.handler
    events:
      - http:
          method: post
          path: realm
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'

  realmAllRegions:
    tags:
      Function: Wah-realmAllRegions
    handler: src/controllers/realm.realmAllRegions
    memorySize: 200
    events:
      - http:
          method: get
          path: realm/all
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  getByRegionAndName:
    tags:
      Function: Wah-getByRegionAndName
    handler: src/controllers/realm.getByRegionAndName
    memorySize: 200
    events:
      - http:
          method: get
          path: realm/{region}/{realm}
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  test:
    tags:
      Function: Wah-test
    handler: src/controllers/test.handler
    memorySize: 512
    events:
      - http:
          method: get
          path: test
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'

  logger:
    tags:
      Function: Wah-logger
    handler: src/controllers/logger.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: logger
  loggerClientEvent:
    tags:
      Function: Wah-loggerClientEvent
    handler: src/controllers/logger.clientEvent
    memorySize: 128
    events:
      - http:
          method: post
          path: logger/client-event
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'

  loggerClientDelete:
    tags:
      Function: Wah-loggerClientDelete
    handler: src/controllers/logger.clientDelete
    memorySize: 128
    events:
      - http:
          method: delete
          path: logger/client-event
          cors:
            origin: 'http://localhost:4200,https://wah.jonaskf.net'
  currency:
    tags:
      Function: Wah-currencies
    handler: src/controllers/currency.handler
    memorySize: 128
    events:
      - http:
          method: any
          path: currency
          cors:
            origin: 'http://localhost:4200'
  updateTSMDumpData:
    tags:
      Function: Wah-updateTSMDumpData
    handler: src/controllers/tsm.handler
    memorySize: 256
